#!/usr/bin/env python3
"""
Generate a mask zip file that is correctly aligned with a dataset zip.

The key steps are:
1. Read dataset.json from the dataset zip to obtain the correct image order and class labels.
2. Map dataset class indices to the corresponding mask sub-directories.
3. Write a mask zip that follows the same order as the dataset.

Usage:
    python prepare_masks_correct.py --dataset colon
    python prepare_masks_correct.py --dataset stomach
"""

import os
import json
import zipfile
import numpy as np
from PIL import Image
from collections import defaultdict
import click


# Category mapping for the Colon dataset:
# dataset class index -> mask sub-directory class index
COLON_CATEGORY_MAPPING = {
    0: 1,  # Dataset cat 0 -> Mask colon_1 (Budding_opaque)
    1: 0,  # Dataset cat 1 -> Mask colon_0 (Budding_transparent)
    2: 3,  # Dataset cat 2 -> Mask colon_3 (Non_budding_opaque)
    3: 2,  # Dataset cat 3 -> Mask colon_2 (Non_budding_transparent)
}

# Category mapping for the Stomach dataset (adjust if needed)
STOMACH_CATEGORY_MAPPING = {
    0: 0,  # Dataset cat 0 -> Mask stomach_0
    1: 1,  # Dataset cat 1 -> Mask stomach_1
}


@click.command()
@click.option('--dataset', type=click.Choice(['colon', 'stomach']), required=True, help='Dataset type')
@click.option('--data-zip', default=None, help='Dataset zip path (optional; inferred by default)')
@click.option('--mask-dir', default=None, help='Mask directory path (optional; inferred by default)')
@click.option('--output', default=None, help='Output zip path (optional; generated by default)')
def main(dataset, data_zip, mask_dir, output):
    """Generate a correctly ordered mask zip file for the given dataset."""

    # Set default paths
    if dataset == 'colon':
        data_zip = data_zip or 'datasets/colon-64x64.zip'
        mask_dir = mask_dir or 'mask/colon'
        output = output or 'datasets/colon-masks-64x64-correct.zip'
        category_mapping = COLON_CATEGORY_MAPPING
        mask_prefix = 'colon_'
    else:  # stomach
        data_zip = data_zip or 'datasets/stomach-64x64.zip'
        mask_dir = mask_dir or 'mask/stomach'
        output = output or 'datasets/stomach-masks-64x64-correct.zip'
        category_mapping = STOMACH_CATEGORY_MAPPING
        mask_prefix = 'stomach_'

    print(f"Dataset:     {dataset}")
    print(f"Dataset zip: {data_zip}")
    print(f"Mask dir:    {mask_dir}")
    print(f"Output:      {output}")
    print()

    # 1. Read dataset.json from the dataset zip
    print("Reading dataset info...")
    with zipfile.ZipFile(data_zip, 'r') as zf:
        with zf.open('dataset.json') as f:
            dataset_info = json.load(f)

    labels_list = dataset_info['labels']  # [[filename, category], ...]
    print(f"  Images: {len(labels_list)}")

    # Count per-class samples
    category_counts = defaultdict(int)
    for fname, cat in labels_list:
        category_counts[cat] += 1
    print(f"  Class distribution: {dict(category_counts)}")

    # 2. Load all mask files grouped by class
    print("\nLoading mask files...")
    mask_files_by_category = defaultdict(list)

    for subdir in sorted(os.listdir(mask_dir)):
        subdir_path = os.path.join(mask_dir, subdir)
        if not os.path.isdir(subdir_path):
            continue

        # Extract class index from sub-directory name
        if subdir.startswith(mask_prefix):
            try:
                mask_cat = int(subdir.split('_')[1])
            except Exception:
                continue

            mask_files = sorted([f for f in os.listdir(subdir_path) if f.endswith('.png')])
            mask_files_by_category[mask_cat] = [(os.path.join(subdir_path, f), f) for f in mask_files]
            print(f"  {subdir}: {len(mask_files)} mask files")

    # 3. Validate counts match
    print("\nValidating counts...")
    for dataset_cat, count in category_counts.items():
        mask_cat = category_mapping.get(dataset_cat, dataset_cat)
        mask_count = len(mask_files_by_category.get(mask_cat, []))
        status = "OK" if count == mask_count else "MISMATCH"
        print(f"  Dataset class {dataset_cat} ({count}) -> Mask class {mask_cat} ({mask_count}) [{status}]")

        if count != mask_count:
            print(f"    Warning: count mismatch!")

    # 4. Write mask zip in dataset order
    print("\nGenerating mask zip...")

    mask_indices = defaultdict(int)

    os.makedirs(os.path.dirname(output) or '.', exist_ok=True)

    with zipfile.ZipFile(output, 'w', zipfile.ZIP_DEFLATED) as out_zf:
        for i, (img_fname, dataset_cat) in enumerate(labels_list):
            mask_cat = category_mapping.get(dataset_cat, dataset_cat)
            mask_list = mask_files_by_category.get(mask_cat, [])

            if not mask_list:
                print(f"  Warning: no masks for class {mask_cat}, using all-white mask")
                mask = np.ones((64, 64), dtype=np.uint8) * 255
            else:
                idx = mask_indices[mask_cat]
                if idx >= len(mask_list):
                    print(f"  Warning: masks exhausted for class {mask_cat}, cycling")
                    idx = idx % len(mask_list)

                mask_path, mask_fname = mask_list[idx]
                mask_indices[mask_cat] += 1

                # Load and resize mask to 64x64
                mask = Image.open(mask_path).convert('L')
                mask = mask.resize((64, 64), Image.BILINEAR)
                mask = np.array(mask)

            # Save with the same base name as the image
            img_basename = os.path.basename(img_fname)
            img_name = os.path.splitext(img_basename)[0]
            mask_out_fname = f"{img_name}.png"

            mask_img = Image.fromarray(mask)
            import io
            buf = io.BytesIO()
            mask_img.save(buf, format='PNG')
            out_zf.writestr(mask_out_fname, buf.getvalue())

            if (i + 1) % 500 == 0:
                print(f"  Progress: {i+1}/{len(labels_list)}")

    print(f"\nDone! Output: {output}")

    # 5. Verify output zip
    print("\nVerifying output zip...")
    with zipfile.ZipFile(output, 'r') as zf:
        mask_files = [f for f in zf.namelist() if f.endswith('.png')]
        print(f"  Mask count: {len(mask_files)}")

        first_mask = mask_files[0]
        with zf.open(first_mask) as f:
            img = Image.open(f)
            print(f"  First mask: {first_mask}, size: {img.size}")


if __name__ == '__main__':
    main()
